Use `-O` option for storing `wget` output to avoid caching
Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra pull request #17
Opened 2021-06-26 04:59 UTC by BrunoGrandePhD

Prompted by Sage-Bionetworks/scicomp-provisioner#487.

2021-06-27 03:02 UTC, zaro0508 requested changes

2021-06-29 18:36 UTC, tthyer approved these changes

2021-06-29 21:22 UTC, BrunoGrandePhD commented
@tthyer @zaro0508: Can either of you confirm that a folder created during a GH CI workflow persists in subsequent steps? I'm 95% sure that the file system persists between steps but not between jobs, but I still would like to confirm.

2021-06-29 21:41 UTC, zaro0508 approved these changes
yes, file system persists between steps but not jobs.

2021-06-30 04:01 UTC, merged