[IT-2360] Setup IAM roles for tower
Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra pull request #181
Opened 2023-04-10 21:12 UTC by zaro0508

Allow tower to use roles instead of a service user to access AWS resources.

2023-05-16 15:23 UTC, BrunoGrandePhD requested changes
As I mentioned in one of the comments, this IAM role would need to get deployed once per Tower project. It's intended to replace the [IAM user](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/8b8da9b40a9a82bbb2f18ad356ad684e07cd8216/templates/tower-project.j2#L94-L118) that's currently in the `tower-project.j2` template. However, I acknowledge that this template has grown to be quite large, so we can discuss how we should organize the resources if you think it's unmanageable. I know you're not a fan of nested stacks. I'll let you decide if you want to keep `tower-project.j2` as a "monolith" or not. 

If you need clarification, we can discuss on Slack.

2023-05-16 15:23 UTC, BrunoGrandePhD commented on templates/nextflow-tower-role.yaml
> +  ManagedPolicy:
These policies already exist here: [nextflow-forge-iam-policy.yaml](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/dev/config/common/nextflow-forge-iam-policy.yaml) and [nextflow-launch-iam-policy.yaml](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/dev/config/common/nextflow-launch-iam-policy.yaml). So, there's no need to deploy them again.

2023-05-16 15:23 UTC, BrunoGrandePhD commented on config/infra-dev/nextflow-tower-role.yaml
> +    - !stack_output infra-dev/nextlfow-tower-config-bucket.yaml::BucketArn
This role would get created once per Tower project/workspace and would be granted permissions on the S3 buckets for each Tower project. This role does not need access to the Tower config bucket, which is only used by the Tower web app.

2023-05-16 15:23 UTC, BrunoGrandePhD commented on templates/nextflow-tower-role.yaml
> +      AssumeRolePolicyDocument:
Once this role is set up for each Tower workspace, I think it'll need to be "assumable" by the Tower ECS role. There are a few IAM roles related to ECS, so I'm not 100% sure which one needs to be trusted. Here's [my guess](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/8b8da9b40a9a82bbb2f18ad356ad684e07cd8216/templates/nextflow-ecs-service.yaml#L54-L79).

2023-05-16 15:23 UTC, BrunoGrandePhD requested changes
As I mentioned in one of the comments, this IAM role would need to get deployed once per Tower project. It's intended to replace the [IAM user](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/8b8da9b40a9a82bbb2f18ad356ad684e07cd8216/templates/tower-project.j2#L94-L118) that's currently in the `tower-project.j2` template. However, I acknowledge that this template has grown to be quite large, so we can discuss how we should organize the resources if you think it's unmanageable. I know you're not a fan of nested stacks. I'll let you decide if you want to keep `tower-project.j2` as a "monolith" or not. 

If you need clarification, we can discuss on Slack.

2023-05-18 22:08 UTC, zaro0508 commented on config/infra-dev/nextflow-tower-role.yaml
> +    - !stack_output infra-dev/nextlfow-tower-config-bucket.yaml::BucketArn
i have moved the resources into tower-project.j2

2023-05-18 22:08 UTC, zaro0508 commented on templates/nextflow-tower-role.yaml
> +  ManagedPolicy:
changed to use existing policies.

2023-05-18 22:09 UTC, zaro0508 commented on templates/nextflow-tower-role.yaml
> +      AssumeRolePolicyDocument:
gave ECS role permission to assume tower role

2023-05-25 20:34 UTC, thomasyu888 approved these changes
LGTM!

2023-06-08 14:08 UTC, merged