Create nf-test.yaml
Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra pull request #239
Opened 2023-09-15 22:22 UTC by allaway

Trying to debug why we cannot use external buckets on nextflow in nf-add5-project.

2023-09-15 22:26 UTC, thomasyu888 requested changes
Can we actually try this in the dev space? So project-dev.

2023-09-15 22:29 UTC, allaway commented
@thomasyu888, I was thinking the same thing  at first , but I was also wondering if that might affect testing (i.e. isn't that a differnt AWS account entirely?)

2023-09-16 00:41 UTC, thomasyu888 approved these changes

2023-09-16 00:42 UTC, thomasyu888 reviewed
I will merge, then I'll have to push to prod branch to trigger the production ci/cd.

2023-09-16 00:42 UTC, merged