[IT-3184] Setup Elasticache for nextflow
Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra pull request #250
Opened 2023-10-17 18:35 UTC by zaro0508

Per nextflow issue[1], Seqera suggest we use AWS elasticache with Redis
instead of hosting redis in a docker container.  This step is to
setup Elasticache for nextflow.

Note: once setup, we will need to configure nextflow'S TOWER_REDIS_URL[2]
parameter to use the AWS-generated endpoint. The backend and cron containers
need to be aware of this configuration in the environment section of the ECS template.

example:
```
## tower.env. I have enabled the encryption for this Redis instance.
TOWER_REDIS_URL=rediss://mp-cache-0001-001.mp-cache.3pconu.use1.cache.amazonaws.com:6379
```

[1] https://support.seqera.io/support/tickets/4048
[2] https://help.tower.nf/23.2/enterprise/configuration/overview/#tower-and-redis-databases:~:text=TOWER_REDIS_URL,redis%3A//redis%3A6379

2023-10-17 19:14 UTC, xschildw approved these changes

2023-10-17 23:36 UTC, jesusaurus requested changes

2023-10-17 23:36 UTC, jesusaurus commented on templates/nextflow-elasticache-cluster.yaml
> +      SecurityGroupIngress: !Ref SecurityGroupIngress
I think this value needs to be a single item list

2023-10-18 00:03 UTC, jesusaurus approved these changes

2023-10-18 00:25 UTC, xschildw approved these changes

2023-10-18 00:26 UTC, merged