Add VPC
Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra pull request #5
Opened 2021-04-15 22:08 UTC by tthyer

Add a VPC for NextFlow.

2021-04-15 22:32 UTC, BrunoGrandePhD approved these changes
🚀 

For my own curiosity, we're not bothering with tagging the VPC with `Department` and `Project` because it doesn't cost anything, right?

2021-04-15 23:06 UTC, tthyer commented
@BrunoGrandePhD Deliberately not tagging because these have default values that seem more appropriate (i.e., IT infrastructure) rather than to a Science department and individual. See the template starting at [line 27](https://github.com/Sage-Bionetworks/aws-infra/blob/v0.2.3/templates/vpc.yaml#L27).

2021-04-16 14:05 UTC, zaro0508 requested changes

2021-04-16 14:05 UTC, zaro0508 commented on config/prod/nextflow-vpc.yaml
> +  VpcSubnetPrefix: "10.41"
Here is our list of VPCs https://sagebionetworks.jira.com/wiki/spaces/IT/pages/352976898/Sage+VPN.  

You'll just need to pick a value that isn't on the list, so how about  `172.21`?   When you decide on a value please add it to the wiki.

2021-04-16 17:47 UTC, zaro0508 requested changes
Can we hold off on this?  IT needs to think about this a little more.  We think using a vpc.yaml for this is not appropriate and are discussing alternatives.

2021-04-19 22:52 UTC, tthyer commented
Closing this pull request -- will open a new one when a new [medium-sized VPC template](https://github.com/Sage-Bionetworks/aws-infra/pull/293) is available.

2021-04-19 22:52 UTC, closed without merging